#!/usr/bin/with-contenv /bin/sh
# shellcheck shell=sh

# pass configuration environment variables to phpmyadmin without
# exposing the entire container environment
ENV_INI_FILE="/etc/phpmyadmin/env.ini"

for var in $(env | grep PMA_); do
	sed -i "s|${var%=*}\s*=\s*.*|${var%=*} = ${var#*=}|g" $ENV_INI_FILE
done

# the variables below should be made to be configuratble via the environment
# but that'll need to happen in the upstream base images

# this is currently set statically in default.conf
# sed -E \
# 	-e "s|^(\s*)client_max_body_size.*|\1client_max_body_size 100m;|g" \
# 	-i /etc/nginx/nginx.conf

sed -E \
	-e 's|^\s?pm.max_children\s.*|pm.max_children = 10|' \
	-i "/etc/${PHP_PACKAGE}/php-fpm.d/www.conf"

sed -E \
	-e 's|^(max_execution_time).*|\1 = 600|' \
	-e 's|^(upload_max_filesize).*|\1 = 100M|' \
	-e 's|^(post_max_size).*|\1 = 100M|' \
	-i "/etc/${PHP_PACKAGE}/php.ini"
