#!/usr/bin/env bash

. hooks/env

arg_string=''

[ ! -z "${PHP_VERSION}" ] && arg_string="${arg_string} --build-arg PHP_VERSION=${PHP_VERSION}"
[ ! -z "${TARGET_VERSION}" ] && arg_string="${arg_string} --build-arg PMA_VERSION=${TARGET_VERSION}"

build_cmd=(docker build ${arg_string} -t ${IMAGE_NAME} .)

printf '\n---\n%s\n---\n\n' "${build_cmd[*]}"
"${build_cmd[@]}"
